# Generated by Django 4.0.4 on 2022-09-06 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfectionDay',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('real_infection', models.IntegerField(null=True)),
                ('pred_infection', models.IntegerField(null=True)),
                ('inputs', models.ManyToManyField(to='infection_days.infectionday')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
